### ISSUE TITLE
Up and Down Arrow not working in "Client’s Feedback About Me" Section

### ISSUE THREAD

**Issue by kmlhsn** [front-end-by-rimantas/19-grupe-portfolio-personal#129]
Up and Down Arrow not working in "Client’s Feedback About Me" Section

![image](https://user-images.githubusercontent.com/32615215/103140077-8c107300-470c-11eb-8c03-a6db68c64bbb.png)

**Comment by belauzas** [comment]
Please check current issues list, before creating new #125
