### ISSUE TITLE
Links under "Latest Posts From Our Blog" do not redirect to blog detail page

### ISSUE THREAD

**Issue by kmlhsn** [front-end-by-rimantas/19-grupe-portfolio-personal#130]
If I click Links() under "Latest Posts From Our Blog" do not redirect to blog detail page.
![image](https://user-images.githubusercontent.com/32615215/103140141-44d6b200-470d-11eb-8500-ef6a728e1f25.png)

**Comment by belauzas** [comment]
Thanks, it's not part of a project requirements yet
