### ISSUE TITLE
" Client’s Feedback About Me" -Content div going over fixed navbar 

### ISSUE THREAD

**Issue by kmlhsn** [front-end-by-rimantas/19-grupe-portfolio-personal#132]
" Client’s Feedback About Me" -Content div going over fixed navbar when scrolling down

![image](https://user-images.githubusercontent.com/32615215/103140401-5ff6f100-4710-11eb-8eed-1d15c2cd3ec0.png)

**Comment by belauzas** [comment]
Thanks, need to check if this is not a duplicate with #68

**Comment by anavisnia** [comment]
> " Client’s Feedback About Me" -Content div going over fixed navbar when scrolling down
> 
> ![image](https://user-images.githubusercontent.com/32615215/103140401-5ff6f100-4710-11eb-8eed-1d15c2cd3ec0.png)

Hi, thank you for the notice!
We have resolved this issue. Our link is not updated yet.
